const STATUS_OK = 201;
const ERROR_BADREQUEST = 400;
const ERROR_AUTH = 401;
const ERROR_ACCESS = 403;
const ERROR_NOTFOUND = 404;
const ERROR_CONFLICT = 409;
const ERROR_DEFAULT = 500;
const ERROR_CODE_UNIQUE = 11000;

module.exports = {
  STATUS_OK,
  ERROR_BADREQUEST,
  ERROR_AUTH,
  ERROR_ACCESS,
  ERROR_NOTFOUND,
  ERROR_CONFLICT,
  ERROR_DEFAULT,
  ERROR_CODE_UNIQUE,
};
